meta_product_name: "Step by StApp"
meta_title: "Step by StApp - Change your life by establishing good habits"
meta_description: "Set goals, motivate yourself and feel part of a community that is ambitious to improve themselves."
meta_image: "favicon.png" # should exist in `app/assets/images/`